#!/bin/bash
#
DOCROOT=`grep -Po '^chdir = \K.*' /etc/php-fpm.d/www.conf 2>/dev/null`
if [ -z ${DOCROOT} ];then
	DOCROOT="/usr/local/emhttp"
fi

# Copy config files to ram file system.
${DOCROOT}/plugins/unassigned.devices/scripts/copy_config.sh

logger "Mounting 'Auto Mount' Devices..." -t"unassigned.devices"
${DOCROOT}/plugins/unassigned.devices/scripts/rc.unassigned mount autodevices
