#!/bin/bash
#
DOCROOT=`grep -Po '^chdir = \K.*' /etc/php-fpm.d/www.conf 2>/dev/null`
if [ -z ${DOCROOT} ];then
	DOCROOT="/usr/local/emhttp"
fi

logger "Mounting 'Auto Mount' Remote Shares..." -t"unassigned.devices"
${DOCROOT}/plugins/unassigned.devices/scripts/rc.unassigned mount autoshares &
