#!/bin/bash
#
DOCROOT=`grep -Po '^chdir = \K.*' /etc/php-fpm.d/www.conf 2>/dev/null`
if [ -z ${DOCROOT} ];then
	DOCROOT="/usr/local/emhttp"
fi

# Update the shares because Unraid shares have been changed and UD NFS shares need to be re-added to exports
${DOCROOT}/plugins/unassigned.devices/scripts/rc.settings shares &>/dev/null
