#!/usr/bin/php
<?PHP
/* Copyright 2016, Dan Landon.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>

<?
$plugin = "unassigned.devices";
require_once("/usr/local/emhttp/plugins/${plugin}/include/lib.php");

if (isset($_ENV['DEVLINKS'])) {
  foreach (explode(" ", $_ENV['DEVLINKS']) as $link) {
    get_udev_info($link, $_ENV, true);
  }
}
touch($paths['reload']);
?>